In [1]:
import pandas as pd

In [28]:
# ##Step 1: Loading the Dataset

# ##Purpose:
# The cleaned retail dataset is loaded into Python using Pandas to perform cohort analysis.

In [9]:
df=pd.read_csv(r"D:\Datasets\cleaned_retail_data.csv")

In [10]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TransactionMonth,CohortMonth
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850,United Kingdom,2010-12,2010-12
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850,United Kingdom,2010-12,2010-12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850,United Kingdom,2010-12,2010-12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850,United Kingdom,2010-12,2010-12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850,United Kingdom,2010-12,2010-12

In [12]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'TransactionMonth',
       'CohortMonth'],
      dtype='object')

In [15]:
df[['TransactionMonth','CohortMonth']].head()

  TransactionMonth CohortMonth
0          2010-12     2010-12
1          2010-12     2010-12
2          2010-12     2010-12
3          2010-12     2010-12
4          2010-12     2010-12

In [29]:
# Step 2: Converting Month Columns to Date Format

# Purpose:
# TransactionMonth and CohortMonth are converted into datetime format so that month-based calculations can be performed accurately.

In [16]:
df['TransactionMonth']=pd.to_datetime(df['TransactionMonth'])
df['CohortMonth']=pd.to_datetime(df['CohortMonth'])

In [ ]:
# Step 3: Calculating Cohort Index

# Purpose:
# CohortIndex represents the number of months elapsed since a customer's first purchase.

In [18]:
df['CohortIndex'] = (
    (df['TransactionMonth'].dt.year - df['CohortMonth'].dt.year) * 12
    + (df['TransactionMonth'].dt.month - df['CohortMonth'].dt.month)
)

In [ ]:
# Step 4: Verifying Cohort Index

# Purpose:
# To ensure that the CohortIndex has been calculated correctly for each transaction.

In [19]:
df[['TransactionMonth','CohortMonth','CohortIndex']].head()

  TransactionMonth CohortMonth  CohortIndex
0       2010-12-01  2010-12-01          0.0
1       2010-12-01  2010-12-01          0.0
2       2010-12-01  2010-12-01          0.0
3       2010-12-01  2010-12-01          0.0
4       2010-12-01  2010-12-01          0.0

In [30]:
# Step 5: Grouping Customers

# Purpose:
# Customers are grouped according to their CohortMonth and CohortIndex.

In [20]:
cohort_data = df.groupby(
    ['CohortMonth', 'CohortIndex']
)['CustomerID'].nunique().reset_index()

In [ ]:
# Step 8: Final Cohort Table

# Purpose:
# The final cohort table is generated and used for retention analysis and cohort matrix creation.

In [22]:
cohort_data.head(10)

  CohortMonth  CohortIndex  CustomerCount
0  2010-12-01          0.0            644
1  2010-12-01          1.0            127
2  2010-12-01          2.0            124
3  2010-12-01          3.0            122
4  2010-12-01          4.0            129
5  2010-12-01          5.0            140
6  2010-12-01          6.0            137
7  2010-12-01          7.0            118
8  2010-12-01          8.0            125
9  2010-12-01          9.0            138

In [ ]:
# Final Step to update the csv file with applied changes.

In [24]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\sshan\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\sshan\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [25]:
df.to_csv(r"D:\Datasets\cleaned_retail_data_updated.csv", index=False)

In [26]:
cohort_data.head(20)

   CohortMonth  CohortIndex  CustomerCount
0   2010-12-01          0.0            644
1   2010-12-01          1.0            127
2   2010-12-01          2.0            124
3   2010-12-01          3.0            122
4   2010-12-01          4.0            129
5   2010-12-01          5.0            140
6   2010-12-01          6.0            137
7   2010-12-01          7.0            118
8   2010-12-01          8.0            125
9   2010-12-01          9.0            138
10  2010-12-01         10.0            142
11  2010-12-01         11.0            181
12  2010-12-01         12.0            175
13  2011-01-01          0.0            178
14  2011-01-01          1.0             26
15  2011-01-01          2.0             24
16  2011-01-01          3.0             22
17  2011-01-01          4.0             35
18  2011-01-01          5.0             39
19  2011-01-01          6.0             23